[package]
name = "rumya-binding"
version = "0.1.4"
edition = "2021"
authors = ["梶塚太智 <kajizukataichi@outlook.jp>"]
description = "Rumya programming language's binding for Rust"
license = "MIT"

[dependencies]
